CrudBasic.Web/Models/ClienteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CrudBasic.Web.Models
{
    public class ClienteViewModel
    {
        public long Id { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        public string Endereco { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Uf { get; set; }
    }
}

CrudBasic.Web/Models/ProdutoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CrudBasic.Web.Models
{
    public class ProdutoViewModel
    {
        public long Id { get; set; }
        public string CodigoBarra { get; set; }
        public string Descricao { get; set; }
        public decimal Valor { get; set; }
    }
}

CrudBasic.Web/Models/VendaDetalheViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CrudBasic.Web.Models
{
    public class VendaDetalheViewModel
    {
        public long Id { get; set; }
        [Required]
        public virtual ProdutoViewModel Produto { get; set; }
        public decimal Desconto { get; set; }
        [Required]
        public decimal ValorTotal { get; set; }
    }
}

CrudBasic.Web/Models/VendaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CrudBasic.Web.Models
{
    public class VendaViewModel
    {
        public long Id { get; set; }
        [Required]
        public DateTime Data { get; set; }
        [Required]
        public ClienteViewModel Cliente { get; set; }
        public IEnumerable<VendaDetalheViewModel> DetalheDaVenda { get; set; }
        [Required]
        public decimal TotalVenda { get; set; }
    }
}

CrudBasic.Web/Controllers/ClientesController.cs
using AutoMapper;
using CrudBasic.Core.DTO;
using CrudBasic.Core.Interfaces.Services;
using CrudBasic.Web.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CrudBasic.Web.Controllers
{
    public class ClientesController : Controller
    {
        private readonly IClientesServices _clientesServices;
        public ClientesController(IClientesServices clientesServices) => _clientesServices = clientesServices;

        public ActionResult Index() => View(Mapper.Map<IEnumerable<ClienteViewModel>>(_clientesServices.ListarTodos()));

        public ActionResult Details(int id) => View(Mapper.Map<ClienteViewModel>(_clientesServices.GetById(id)));

        public ActionResult Create() => View();

        [HttpPost]
        public ActionResult Create(ClienteViewModel cliente)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _clientesServices.Criar(Mapper.Map<ClienteDTO>(cliente));
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id) => View(Mapper.Map<ClienteViewModel>(_clientesServices.GetById(id)));

        [HttpPost]
        public ActionResult Edit(int id, ClienteViewModel cliente)
        {
            try
            {
                _clientesServices.Alterar(Mapper.Map<ClienteDTO>(cliente));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id) => View(Mapper.Map<ClienteViewModel>(_clientesServices.GetById(id)));

        [HttpPost]
        public ActionResult Delete(int id, ClienteViewModel cliente)
        {
            try
            {
                _clientesServices.Excluir(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CrudBasic.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrudBasic.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CrudBasic.Web/Controllers/ProdutosController.cs
using AutoMapper;
using CrudBasic.Core.DTO;
using CrudBasic.Core.Interfaces.Services;
using CrudBasic.Web.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CrudBasic.Web.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly IProdutosService _produtosServices;

        public ProdutosController(IProdutosService produtosServices) => _produtosServices = produtosServices;

        public ActionResult Index() => View(Mapper.Map<IEnumerable<ProdutoViewModel>>(_produtosServices.ListarTodos()));

        public ActionResult Details(int id) => View(Mapper.Map<ProdutoViewModel>(_produtosServices.GetById(id)));

        public ActionResult Create() => View();

        [HttpPost]
        public ActionResult Create(ProdutoViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _produtosServices.Criar(Mapper.Map<ProdutoDTO>(model));
                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id) => View(Mapper.Map<ProdutoViewModel>(_produtosServices.GetById(id)));

        [HttpPost]
        public ActionResult Edit(int id, ProdutoViewModel model)
        {
            try
            {
                _produtosServices.Alterar(Mapper.Map<ProdutoDTO>(model));
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id) => View(Mapper.Map<ProdutoViewModel>(_produtosServices.GetById(id)));

        [HttpPost]
        public ActionResult Delete(int id, ProdutoViewModel model)
        {
            try
            {
                _produtosServices.Excluir(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

CrudBasic.Web/Views/Clientes/Create.cshtml
@model CrudBasic.Web.Models.ClienteViewModel

@{
    ViewBag.Title = "Cliente";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h4>Novo Cliente</h4>
    <hr />

    <div class="form-horizontal" style="margin-right: 2px;">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uf, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<div class="col-md-offset-2 col-md-10">
    <button class="ui-button ui-widget ui-corner-all" data-bind="click: Salvar">Salvar</button>
    <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Index", "Clientes")+"'");">Cancelar</button>
</div>
<div style="display: none">
    <div id="dialog-confirm" title="Confirmação">
        <p data-bind="text: messageConfirmacao"><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span></p>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/Class.js"></script>
<script src="~/Scripts/Configuration.js"></script>
<script src="~/Scripts/ViewModels/ClienteViewModel.js"></script>
<script src="~/Scripts/ViewModels/ClienteEditViewModel.js"></script>
<script type="text/javascript">
    ko.applyBindings(new window.CB.Models.ClienteEditViewModel());
</script>

CrudBasic.Web/Views/Clientes/Delete.cshtml
@model CrudBasic.Web.Models.ClienteViewModel

<h3>Deseja excluir os dados deste cliente?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uf)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    }
    <div class="col-md-offset-2 col-md-10">
        <button class="ui-button ui-widget ui-corner-all" data-bind="click: Delete">Excluir</button>
        <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Index", "Clientes")+"'");">Cancelar</button>
    </div>
    <div style="display: none">
        <div id="dialog-confirm" title="Confirmação">
            <p data-bind="text: messageConfirmacao"><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span></p>
        </div>
    </div>
</div>
<script src="~/Scripts/Class.js"></script>
<script src="~/Scripts/Configuration.js"></script>
<script src="~/Scripts/ViewModels/ClienteEditViewModel.js"></script>
<script type="text/javascript">
    ko.applyBindings(new window.CB.Models.ClienteEditViewModel());
</script>

CrudBasic.Web/Views/Clientes/Details.cshtml
@model CrudBasic.Web.Models.ClienteViewModel

<div>
    <h4>Detalhes do Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Endereco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Uf)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Uf)
        </dd>

    </dl>
</div>
<p>
    <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Edit/"+Model.Id, "Clientes") + "'");">Editar</button>
    <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Index", "Clientes")+"'");">Voltar</button>
</p>
<script src="~/Scripts/Class.js"></script>
<script src="~/Scripts/Configuration.js"></script>
<script src="~/Scripts/ViewModels/ClienteEditViewModel.js"></script>
<script type="text/javascript">
    ko.applyBindings(new window.CB.Models.ClienteEditViewModel());
</script>

CrudBasic.Web/Views/Clientes/Edit.cshtml
@model CrudBasic.Web.Models.ClienteViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Alterar Dados do Cliente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Bairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Bairro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Bairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Uf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Uf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Uf, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}

    <div class="col-md-offset-2 col-md-10">
        <button class="ui-button ui-widget ui-corner-all" data-bind="click: Salvar">Salvar</button>
        <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Index", "Clientes")+"'");">Cancelar</button>
    </div>
<div style="display: none">
    <div id="dialog-confirm" title="Confirmação">
        <p data-bind="text: messageConfirmacao"><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span></p>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/Class.js"></script>
<script src="~/Scripts/Configuration.js"></script>
<script src="~/Scripts/ViewModels/ClienteEditViewModel.js"></script>
<script type="text/javascript">
    ko.applyBindings(new window.CB.Models.ClienteEditViewModel());
</script>

CrudBasic.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Página Principal";
}

CrudBasic.Web/Views/Produtos/Create.cshtml
@model CrudBasic.Web.Models.ProdutoViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Novo Cliente</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ProdutoViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CodigoBarra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoBarra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoBarra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<div class="col-md-offset-2 col-md-10">
    <button class="ui-button ui-widget ui-corner-all" data-bind="click: Salvar">Salvar</button>
    <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Index", "Produtos")+"'");">Cancelar</button>
</div>
<div style="display: none">
    <div id="dialog-confirm" title="Confirmação">
        <p data-bind="text: messageConfirmacao"><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span></p>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/Class.js"></script>
<script src="~/Scripts/Configuration.js"></script>
<script src="~/Scripts/ViewModels/ProdutoEditViewModel.js"></script>
<script type="text/javascript">
    ko.applyBindings(new window.CB.Models.ProdutoEditViewModel());
</script>

CrudBasic.Web/Views/Produtos/Delete.cshtml
@model CrudBasic.Web.Models.ProdutoViewModel
<h3>Deseja excluir os dados deste cliente?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CodigoBarra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodigoBarra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
    }
    <div class="col-md-offset-2 col-md-10">
        <button class="ui-button ui-widget ui-corner-all" data-bind="click: Delete">Excluir</button>
        <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Index", "Produtos")+"'");">Cancelar</button>
    </div>
    <div style="display: none">
        <div id="dialog-confirm" title="Confirmação">
            <p data-bind="text: messageConfirmacao"><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span></p>
        </div>
    </div>
</div>
<script src="~/Scripts/Class.js"></script>
<script src="~/Scripts/Configuration.js"></script>
<script src="~/Scripts/ViewModels/ProdutoEditViewModel.js"></script>
<script type="text/javascript">
    ko.applyBindings(new window.CB.Models.ProdutoEditViewModel());
</script>

CrudBasic.Web/Views/Produtos/Details.cshtml
@model CrudBasic.Web.Models.ProdutoViewModel

@{
    ViewBag.Title = "Produto";
}

<h2>Detalhes do Produto</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CodigoBarra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodigoBarra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>
</div>
<p>
    <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Edit/"+Model.Id, "Produtos") + "'");">Editar</button>
    <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Index", "Produtos")+"'");">Voltar</button>
</p>
<script src="~/Scripts/Class.js"></script>
<script src="~/Scripts/Configuration.js"></script>
<script src="~/Scripts/ViewModels/ProdutoEditViewModel.js"></script>
<script type="text/javascript">
    ko.applyBindings(new window.CB.Models.ProdutoEditViewModel());
</script>

CrudBasic.Web/Views/Produtos/Edit.cshtml
@model CrudBasic.Web.Models.ProdutoViewModel

@{
    ViewBag.Title = "Produto";
}

<h2>Alterar Dados do Produto</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CodigoBarra, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoBarra, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoBarra, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<div class="col-md-offset-2 col-md-10">
    <button class="ui-button ui-widget ui-corner-all" data-bind="click: Salvar">Salvar</button>
    <button class="ui-button ui-widget ui-corner-all" onclick="@("window.location.href='" + @Url.Action("Index", "Produtos")+"'");">Cancelar</button>
</div>
<div style="display: none">
    <div id="dialog-confirm" title="Confirmação">
        <p data-bind="text: messageConfirmacao"><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span></p>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts/Class.js"></script>
<script src="~/Scripts/Configuration.js"></script>
<script src="~/Scripts/ViewModels/ProdutoEditViewModel.js"></script>
<script type="text/javascript">
    ko.applyBindings(new window.CB.Models.ProdutoEditViewModel());
</script>